import { Platform, StyleSheet } from 'react-native';
import { DS, tabRootTitleText } from '../../designSystem';
import type { AccessibleColors } from '../../lib/accessibilityTheme';

export type CommunityStyles = ReturnType<typeof createCommunityStyles>;

export function createCommunityStyles(c: AccessibleColors, _textScale: number) {
  return StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: c.background,
  },
  feedHeader: {
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: c.borderWhite5,
  },
  feedHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  communityTitle: {
    ...tabRootTitleText,
  },
  feedHeaderActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: DS.space.lg,
  },
  communityFab: {
    position: 'absolute',
    right: DS.space.base,
    width: 68,
    height: 68,
    borderRadius: 34,
    backgroundColor: c.gold,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 20,
    borderWidth: 2,
    borderColor: 'rgba(0,0,0,0.45)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.35,
    shadowRadius: 6,
    elevation: 8,
  },
  createTop: {
    paddingHorizontal: DS.space.base,
    flexDirection: 'row',
    alignItems: 'center',
    gap: DS.space.md,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: c.borderWhite5,
    paddingBottom: DS.space.md,
  },
  createTitle: {
    flex: 1,
    fontFamily: DS.font.heading,
    fontSize: 14,
    letterSpacing: 2,
    color: c.gold,
    textAlign: 'center',
  },
  createPostBtn: {
    backgroundColor: c.gold,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  createPostBtnTxt: {
    fontFamily: DS.font.bodyMedium,
    color: c.background,
    fontWeight: '700',
  },
  createBody: {
    padding: DS.space.base,
    gap: DS.space.base,
  },
  mediaActionsRow: {
    flexDirection: 'row',
    gap: DS.space.sm,
  },
  createCarousel: {
    gap: DS.space.base,
  },
  createMediaCard: {
    width: 320,
    height: 380,
    borderRadius: DS.radius.xl,
    overflow: 'hidden',
    backgroundColor: c.surface,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: c.borderWhite5,
    marginRight: DS.space.base,
  },
  createMedia: {
    width: '100%',
    height: '100%',
  },
  mediaRemove: {
    position: 'absolute',
    zIndex: 2,
    top: DS.space.sm,
    right: DS.space.sm,
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: 'rgba(0,0,0,0.55)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: c.goldTint30,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  createEmptyMedia: {
    borderRadius: DS.radius.xl,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: c.borderWhite5,
    padding: DS.space.lg,
    backgroundColor: c.surface,
  },
  createEmptyMediaTxt: {
    fontFamily: DS.font.body,
    color: c.textMuted,
  },
  composerSectionKicker: {
    fontFamily: DS.font.bodyMedium,
    fontSize: 11,
    letterSpacing: 1.2,
    color: c.textMuted,
    marginBottom: DS.space.sm,
  },
  composerHero: {
    width: '100%',
    aspectRatio: 4 / 5,
    borderRadius: DS.radius.xl,
    overflow: 'hidden',
    backgroundColor: c.surface,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: c.borderWhite5,
    position: 'relative',
  },
  /** Compact upload preview for create-post (replaces tall 4:5 hero). */
  composerHeroCompact: {
    width: '100%',
    height: 120,
    borderRadius: DS.radius.lg,
    overflow: 'hidden',
    backgroundColor: c.surface,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: c.borderWhite5,
    position: 'relative',
  },
  composerHeroEmptyCompact: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: DS.space.md,
    gap: 4,
  },
  composerHeroEmptyTitleCompact: {
    fontFamily: DS.font.bodyMedium,
    fontSize: 14,
    color: c.text,
    textAlign: 'center',
  },
  composerHeroEmptySubCompact: {
    fontFamily: DS.font.body,
    fontSize: 11,
    color: c.textMuted,
    textAlign: 'center',
  },
  composerHeroInner: {
    width: '100%',
    height: '100%',
  },
  composerHeroEmpty: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: DS.space.xl,
    gap: DS.space.sm,
  },
  composerHeroEmptyTitle: {
    fontFamily: DS.font.bodyMedium,
    fontSize: 17,
    color: c.text,
    textAlign: 'center',
  },
  composerHeroEmptySub: {
    fontFamily: DS.font.body,
    fontSize: 13,
    color: c.textMuted,
    textAlign: 'center',
  },
  composerAddChip: {
    position: 'absolute',
    bottom: DS.space.sm,
    right: DS.space.sm,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: DS.radius.pill,
    backgroundColor: c.gold,
  },
  composerAddChipTxt: {
    fontFamily: DS.font.bodyMedium,
    fontSize: 11,
    color: c.background,
  },
  composerThumbStrip: {
    flexDirection: 'row',
    gap: DS.space.sm,
    paddingVertical: DS.space.xs,
  },
  composerThumbWrap: {
    width: 62,
    height: 62,
    borderRadius: 10,
    overflow: 'hidden',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: c.borderWhite5,
    position: 'relative',
    backgroundColor: c.surface,
  },
  composerThumb: {
    width: '100%',
    height: '100%',
  },
  composerThumbRemove: {
    position: 'absolute',
    top: 2,
    right: 2,
    zIndex: 2,
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: 'rgba(0,0,0,0.62)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: c.goldTint30,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  composerThumbVidBadge: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
    padding: 3,
  },
  captionCard: {
    backgroundColor: c.surface,
    borderRadius: DS.radius.xl,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: c.borderWhite5,
    padding: DS.space.md,
  },
  captionInput: {
    fontFamily: DS.font.body,
    fontSize: 15,
    lineHeight: 22,
    color: c.text,
    minHeight: 90,
    textAlignVertical: 'top',
  },
  eventTagRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: DS.space.sm,
    paddingVertical: DS.space.md,
    paddingHorizontal: DS.space.md,
    borderRadius: DS.radius.xl,
    backgroundColor: c.surfaceAlt,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: c.borderWhite5,
  },
  eventTagTxt: {
    flex: 1,
    fontFamily: DS.font.bodyMedium,
    color: c.text,
  },
  eventPickerOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'flex-end',
  },
  eventPickerBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  eventPickerSheet: {
    backgroundColor: c.background,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    padding: DS.space.lg,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: c.borderWhite5,
    maxHeight: '70%',
  },
  eventPickerTitle: {
    fontFamily: DS.font.heading,
    color: c.gold,
    fontSize: 16,
    letterSpacing: 1,
    marginBottom: DS.space.md,
  },
  eventPickerRow: {
    paddingVertical: DS.space.md,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: c.borderWhite5,
  },
  eventPickerRowTitle: {
    fontFamily: DS.font.bodyMedium,
    color: c.text,
    fontSize: 15,
  },
  eventPickerRowMeta: {
    fontFamily: DS.font.body,
    color: c.textMuted,
    fontSize: 12,
    marginTop: 4,
  },
  notifDot: {
    position: 'absolute',
    top: -2,
    right: -2,
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: c.error,
    borderWidth: 2,
    borderColor: c.background,
  },
  chipsRow: {
    flexDirection: 'row',
    gap: DS.space.md,
    paddingBottom: DS.space.md,
  },
  chip: {
    paddingHorizontal: 20,
    paddingVertical: 6,
    borderRadius: 20,
    borderWidth: 1,
    marginRight: 12,
  },
  chipOn: {
    borderColor: c.gold,
    backgroundColor: c.goldTint10,
  },
  chipOff: {
    borderColor: c.border,
  },
  chipTextOn: {
    fontFamily: DS.font.bodyMedium,
    color: c.gold,
    fontSize: 14,
    fontWeight: '600',
  },
  chipTextOff: {
    fontFamily: DS.font.bodyMedium,
    color: c.textMuted,
    fontSize: 14,
  },
  feedList: {
    paddingHorizontal: DS.space.base,
    paddingTop: DS.space.xs,
    gap: DS.space.base,
  },
  rootWebFull: {
    width: '100%',
    maxWidth: '100%',
  },
  feedWebSplit: {
    flex: 1,
    flexDirection: 'row',
    width: '100%',
    alignItems: 'stretch',
  },
  feedWebColumn: {
    flex: 1,
    width: '100%',
  },
  feedListWebSnap: {
    flexGrow: 1,
  },
  feedWebSnapCell: {
    flex: 1,
    justifyContent: 'center',
    paddingVertical: DS.space.sm,
    width: '100%',
  },
  postAvatarGoldRing: {
    borderWidth: 2,
    borderColor: c.gold,
  },
  feedBanner: {
    backgroundColor: c.goldTint10,
    borderRadius: 10,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: c.postBorderGold20,
    padding: DS.space.md,
    marginBottom: DS.space.base,
  },
  feedBannerText: {
    fontFamily: DS.font.body,
    fontSize: 13,
    lineHeight: 20,
    color: c.text,
  },
  feedEmptyWrap: {
    alignSelf: 'stretch',
    paddingTop: DS.space.sm,
    paddingBottom: DS.space.md,
  },
  feedListEmpty: {
    flexGrow: 0,
  },
  feedEmptyText: {
    fontFamily: DS.font.body,
    fontSize: 14,
    color: c.textMuted,
    textAlign: 'center',
    marginVertical: 0,
  },
  feedSampleKicker: {
    fontFamily: DS.font.bodyMedium,
    fontSize: 12,
    letterSpacing: 0.8,
    color: c.gold,
    textAlign: 'center',
    marginBottom: DS.space.base,
    textTransform: 'uppercase',
  },
  composerWrap: {
    backgroundColor: c.surface,
    borderRadius: 10,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: c.postBorderGold20,
    padding: DS.space.md,
    marginBottom: DS.space.base,
  },
  composerInput: {
    fontFamily: DS.font.body,
    fontSize: 15,
    lineHeight: 22,
    color: c.text,
    minHeight: 72,
    textAlignVertical: 'top',
  },
  composerRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginTop: DS.space.sm,
  },
  attachActions: {
    flexDirection: 'row',
    gap: DS.space.sm,
    marginTop: DS.space.sm,
  },
  attachBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 999,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: c.borderWhite5,
    backgroundColor: c.surfaceAlt,
  },
  attachBtnTxt: {
    fontFamily: DS.font.bodyMedium,
    fontSize: 12,
    color: c.text,
  },
  attachRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: DS.space.sm,
    marginTop: DS.space.sm,
  },
  attachChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: DS.space.sm,
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 999,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: c.borderWhite5,
    backgroundColor: c.surfaceAlt,
    maxWidth: '100%',
  },
  attachThumb: { width: 22, height: 22, borderRadius: 6 },
  attachIcon: {
    width: 22,
    height: 22,
    borderRadius: 6,
    backgroundColor: c.goldTint10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  attachName: {
    fontFamily: DS.font.body,
    fontSize: 12,
    color: c.text,
    maxWidth: 160,
  },
  postButton: {
    backgroundColor: c.gold,
    paddingHorizontal: DS.space.lg,
    paddingVertical: DS.space.sm,
    borderRadius: 8,
  },
  postButtonDisabled: {
    opacity: 0.45,
  },
  postButtonText: {
    fontFamily: DS.font.bodyMedium,
    fontSize: 14,
    fontWeight: '600',
    color: c.background,
  },
  postCard: {
    backgroundColor: c.surface,
    borderRadius: 10,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: c.postBorderGold20,
    padding: DS.space.base,
    marginBottom: DS.space.base,
    ...(Platform.OS === 'web'
      ? { alignSelf: 'stretch' as const, width: '100%' as const, maxWidth: '100%' as const }
      : null),
  },
  postTop: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: DS.space.md,
  },
  postAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    marginRight: DS.space.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: c.borderWhite5,
  },
  postMetaCol: {
    flex: 1,
  },
  postName: {
    fontFamily: DS.font.bodyMedium,
    fontSize: 15,
    color: c.text,
  },
  postTime: {
    fontFamily: DS.font.body,
    fontSize: 11,
    fontWeight: '300',
    color: c.textMuted,
    marginTop: 2,
  },
  postMore: {
    marginLeft: DS.space.sm,
  },
  badge: {
    backgroundColor: c.goldTint10,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
    marginRight: DS.space.sm,
  },
  badgeText: {
    fontFamily: DS.font.bodyMedium,
    fontSize: 10,
    fontWeight: '700',
    color: c.gold,
  },
  postBodyBlock: {
    gap: DS.space.sm,
    marginBottom: 0,
  },
  postBody: {
    fontFamily: DS.font.body,
    fontSize: 14,
    lineHeight: 22,
    color: c.text,
  },
  mentionGold: {
    color: c.gold,
    fontFamily: DS.font.bodyMedium,
    fontWeight: '600',
  },
  mentionTag: {
    color: c.gold,
    fontFamily: DS.font.bodyMedium,
    fontWeight: '700',
  },
  mentionTagMuted: {
    opacity: 0.75,
  },
  clapEmoji: {
    fontSize: 13,
    lineHeight: 16,
  },
  postImage: {
    width: '100%',
    aspectRatio: 16 / 9,
    borderRadius: DS.radius.lg,
    marginTop: DS.space.sm,
  },
  postCarouselWrap: {
    width: '100%',
    marginTop: DS.space.sm,
    borderRadius: DS.radius.lg,
    overflow: 'hidden',
  },
  postCarouselItem: {
    aspectRatio: 16 / 9,
    backgroundColor: c.surfaceAlt,
  },
  postCarouselMedia: {
    width: '100%',
    height: '100%',
  },
  postActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: DS.space.sm,
    paddingTop: DS.space.sm,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: c.borderWhite5,
  },
  postActionsLeft: {
    flexDirection: 'row',
    gap: DS.space.md,
  },
  actionPill: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  actionTxt: {
    fontSize: 12,
    color: c.textMuted,
  },
  topReactionsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: DS.space.sm,
    marginTop: DS.space.xs,
  },
  topReactionTxt: {
    fontSize: 12,
    color: c.textMuted,
  },
  postEventChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    alignSelf: 'flex-start',
    marginBottom: DS.space.sm,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: DS.radius.pill,
    backgroundColor: c.surfaceAlt,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: c.borderWhite5,
    maxWidth: '100%',
  },
  postEventChipTxt: {
    flex: 1,
    fontFamily: DS.font.bodyMedium,
    fontSize: 13,
    color: c.gold,
  },
  commentsModalRoot: {
    flex: 1,
    backgroundColor: c.background,
  },
  commentsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: DS.space.base,
    paddingBottom: DS.space.md,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: c.borderWhite5,
  },
  commentsTitle: {
    fontFamily: DS.font.heading,
    fontSize: 16,
    letterSpacing: 1,
    color: c.text,
  },
  commentsClose: {
    fontFamily: DS.font.bodyMedium,
    fontSize: 16,
    color: c.gold,
  },
  commentsEmpty: {
    fontFamily: DS.font.body,
    fontSize: 14,
    color: c.textMuted,
    paddingVertical: DS.space.lg,
  },
  commentRow: {
    paddingVertical: DS.space.sm,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: c.borderWhite5,
  },
  commentAuthor: {
    fontFamily: DS.font.bodyMedium,
    fontSize: 12,
    color: c.gold,
    marginBottom: 4,
  },
  commentBody: {
    fontFamily: DS.font.body,
    fontSize: 14,
    color: c.text,
    lineHeight: 20,
  },
  commentComposer: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: DS.space.sm,
    paddingHorizontal: DS.space.base,
    paddingTop: DS.space.sm,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: c.borderWhite5,
    backgroundColor: c.surface,
  },
  commentInput: {
    flex: 1,
    minHeight: 40,
    maxHeight: 120,
    borderRadius: DS.radius.lg,
    paddingHorizontal: DS.space.md,
    paddingVertical: DS.space.sm,
    backgroundColor: c.input,
    color: c.text,
    fontSize: 15,
  },
  commentSend: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: c.gold,
    alignItems: 'center',
    justifyContent: 'center',
  },
  searchHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: DS.space.base,
    gap: DS.space.md,
  },
  iconBtn: {
    padding: DS.space.sm,
  },
  searchInput: {
    flex: 1,
    backgroundColor: c.input,
    borderRadius: DS.radius.lg,
    paddingHorizontal: DS.space.base,
    paddingVertical: DS.space.md,
    color: c.text,
    fontSize: 16,
  },
  searchCta: {
    padding: DS.space.lg,
  },
  commSearchBody: {
    paddingHorizontal: DS.space.base,
    paddingTop: DS.space.base,
  },
  commSearchSectionTitle: {
    fontFamily: DS.font.bodyMedium,
    fontSize: 14,
    color: c.text,
    marginBottom: DS.space.md,
    marginTop: DS.space.md,
  },
  recentRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: DS.space.sm,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: c.borderWhite5,
  },
  recentRowLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: DS.space.md,
    flex: 1,
  },
  recentRowText: {
    fontFamily: DS.font.body,
    fontSize: 14,
    color: c.text,
  },
  suggestedTagsWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: DS.space.sm,
    marginBottom: DS.space.md,
  },
  suggestedTag: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: c.border,
  },
  suggestedTagOn: {
    borderColor: c.gold,
    backgroundColor: c.goldTint10,
  },
  suggestedTagTxt: {
    fontFamily: DS.font.bodyMedium,
    fontSize: 14,
    color: c.textMuted,
  },
  suggestedTagTxtOn: {
    color: c.gold,
  },
  trendingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: DS.space.md,
    paddingVertical: DS.space.sm,
  },
  trendingTopic: {
    fontFamily: DS.font.bodyMedium,
    fontSize: 14,
    color: c.text,
  },
  trendingMeta: {
    fontFamily: DS.font.body,
    fontSize: 12,
    color: c.textMuted,
    marginTop: 2,
  },
  commSearchCta: {
    marginTop: DS.space.xl,
    backgroundColor: c.goldTint10,
    borderWidth: 1,
    borderColor: c.gold,
    paddingVertical: DS.space.md,
    borderRadius: DS.radius.lg,
    alignItems: 'center',
  },
  commSearchCtaText: {
    fontFamily: DS.font.bodyMedium,
    fontSize: 16,
    color: c.gold,
  },
  searchHeaderWrap: {
    paddingHorizontal: DS.space.base,
    paddingBottom: DS.space.md,
  },
  searchInputWrap: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: c.surface,
    borderRadius: DS.radius.lg,
    borderWidth: 1,
    borderColor: c.border,
    paddingLeft: 36,
    paddingRight: DS.space.md,
    minHeight: 48,
  },
  searchInputWrapCompact: {
    flex: 1,
    minWidth: 0,
    maxWidth: 300,
  },
  searchHeaderIconSlot: {
    width: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  searchAtModeHint: {
    fontFamily: DS.font.body,
    fontSize: 13,
    color: c.textMuted,
    marginTop: DS.space.xs,
  },
  searchTypeaheadPanel: {
    marginBottom: DS.space.md,
    borderRadius: DS.radius.lg,
    borderWidth: 1,
    borderColor: c.border,
    backgroundColor: c.surface,
    overflow: 'hidden',
  },
  searchSuggestUserRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: DS.space.md,
    paddingVertical: DS.space.md,
    paddingHorizontal: DS.space.base,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: c.borderWhite5,
  },
  searchSuggestAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: c.surfaceAlt,
  },
  searchSuggestName: {
    fontFamily: DS.font.bodyMedium,
    fontSize: 15,
    color: c.text,
  },
  searchSuggestMeta: {
    fontFamily: DS.font.body,
    fontSize: 13,
    color: c.textMuted,
    marginTop: 2,
  },
  searchSuggestPostRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: DS.space.sm,
    paddingVertical: DS.space.md,
    paddingHorizontal: DS.space.base,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: c.borderWhite5,
  },
  searchSuggestPostText: {
    flex: 1,
    fontFamily: DS.font.body,
    fontSize: 14,
    color: c.text,
    lineHeight: 20,
  },
  searchPeopleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: DS.space.md,
    paddingVertical: DS.space.md,
    paddingHorizontal: DS.space.base,
    marginBottom: DS.space.sm,
    borderRadius: DS.radius.lg,
    backgroundColor: c.surface,
    borderWidth: 1,
    borderColor: c.border,
  },
  searchInputIcon: {
    position: 'absolute',
    left: DS.space.base,
    zIndex: 1,
  },
  searchInputInner: {
    flex: 1,
    fontFamily: DS.font.body,
    fontSize: 14,
    color: c.text,
    paddingVertical: DS.space.md,
  },
  searchResultsHeader: {
    paddingHorizontal: DS.space.base,
    paddingBottom: DS.space.md,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: c.borderWhite5,
  },
  searchResultsTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: DS.space.sm,
    marginBottom: DS.space.md,
  },
  searchResultsInputText: {
    flex: 1,
    fontFamily: DS.font.body,
    fontSize: 14,
    color: c.text,
    paddingVertical: 10,
  },
  searchClearHit: {
    padding: DS.space.sm,
  },
  searchBellDot: {
    position: 'absolute',
    top: -2,
    right: -2,
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: c.gold,
  },
  sortRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: DS.space.sm,
    marginBottom: DS.space.md,
  },
  sortLabel: {
    fontFamily: DS.font.body,
    fontSize: 14,
    color: c.textMuted,
  },
  sortChipsInner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: DS.space.sm,
    paddingRight: DS.space.lg,
  },
  sortChip: {
    paddingHorizontal: DS.space.sm,
    paddingVertical: 6,
    borderRadius: DS.radius.sm,
    borderWidth: 1,
    borderColor: c.border,
    backgroundColor: c.surface,
  },
  sortChipOn: {
    borderColor: c.gold,
  },
  sortChipTextOn: {
    fontSize: 13,
    color: c.text,
    fontFamily: DS.font.bodyMedium,
  },
  sortChipTextOff: {
    fontSize: 13,
    color: c.textMuted,
    fontFamily: DS.font.body,
  },
  searchFilterChipsRow: {
    flexDirection: 'row',
    gap: DS.space.sm,
    paddingBottom: DS.space.sm,
  },
  searchFilterChip: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: DS.radius.pill,
    borderWidth: 1,
    borderColor: c.border,
  },
  searchFilterChipOn: {
    borderColor: c.gold,
    backgroundColor: c.goldTint10,
  },
  searchFilterChipTextOn: {
    fontSize: 12,
    color: c.gold,
    fontFamily: DS.font.bodyMedium,
    fontWeight: '600',
  },
  searchFilterChipTextOff: {
    fontSize: 12,
    color: c.textMuted,
    fontFamily: DS.font.bodyMedium,
  },
  searchResultsList: {
    padding: DS.space.base,
  },
  searchResultCount: {
    fontFamily: DS.font.body,
    fontSize: 14,
    color: c.textMuted,
    marginBottom: DS.space.base,
  },
  searchResultCard: {
    backgroundColor: c.surface,
    borderRadius: DS.radius.xl,
    padding: DS.space.base,
    marginBottom: DS.space.base,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: c.borderWhite5,
  },
  searchResultCardTop: {
    flexDirection: 'row',
    gap: DS.space.md,
    marginBottom: DS.space.md,
  },
  searchResultAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
  },
  searchResultNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    marginBottom: 4,
  },
  searchResultName: {
    fontFamily: DS.font.bodyMedium,
    fontSize: 14,
    color: c.text,
  },
  searchResultDot: {
    fontSize: 12,
    color: c.textMuted,
  },
  searchResultTime: {
    fontFamily: DS.font.body,
    fontSize: 12,
    color: c.textMuted,
  },
  resultPostBody: {
    fontFamily: DS.font.body,
    fontSize: 14,
    lineHeight: 22,
    color: c.text,
  },
  resultHighlight: {
    color: c.gold,
    fontFamily: DS.font.bodyMedium,
    fontWeight: '600',
  },
  searchResultMedia: {
    borderRadius: DS.radius.lg,
    overflow: 'hidden',
    marginBottom: DS.space.md,
    backgroundColor: c.background,
    position: 'relative',
  },
  searchResultMediaImg: {
    width: '100%',
    aspectRatio: 16 / 9,
  },
  searchResultPlay: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.35)',
  },
  searchResultActions: {
    flexDirection: 'row',
    gap: DS.space.base,
    alignItems: 'center',
  },
  searchResultAction: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  searchResultActionTxt: {
    fontSize: 13,
    color: c.textMuted,
    fontFamily: DS.font.body,
  },
  notifHeader: {
    paddingHorizontal: DS.space.base,
    paddingBottom: DS.space.md,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: c.borderWhite5,
  },
  notifHeaderTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: DS.space.md,
  },
  notifTitle: {
    ...tabRootTitleText,
    flex: 1,
    textAlign: 'center',
  },
  notifClose: {
    width: 40,
    alignItems: 'flex-end',
  },
  notifHeaderActions: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  markAllRead: {
    fontFamily: DS.font.bodyMedium,
    fontSize: 14,
    color: c.gold,
  },
  notifClear: {
    fontFamily: DS.font.bodyMedium,
    fontSize: 14,
    color: c.gold,
    fontWeight: '600',
  },
  notifItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: DS.space.md,
    padding: DS.space.base,
    borderLeftWidth: 2,
  },
  notifItemUnread: {
    backgroundColor: 'rgba(28, 28, 28, 0.5)',
    borderLeftColor: c.gold,
  },
  notifItemRead: {
    borderLeftColor: 'transparent',
  },
  notifAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
  },
  notifIconCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: c.goldTint10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  notifTextCol: {
    flex: 1,
    minWidth: 0,
  },
  notifBodyLine: {
    fontFamily: DS.font.body,
    fontSize: 14,
    lineHeight: 22,
    color: c.text,
  },
  notifTime: {
    fontFamily: DS.font.body,
    fontSize: 12,
    color: c.textMuted,
    marginTop: 4,
  },
  notifUnreadDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: c.gold,
    marginTop: 8,
  },
  inboxHeader: {
    paddingHorizontal: DS.space.base,
    paddingBottom: DS.space.md,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: c.borderWhite5,
  },
  inboxHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: DS.space.md,
  },
  inboxTitle: {
    ...tabRootTitleText,
    flex: 1,
    textAlign: 'center',
  },
  inboxSearchWrap: {
    position: 'relative',
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: c.surface,
    borderRadius: DS.radius.lg,
    borderWidth: 1,
    borderColor: c.border,
    paddingLeft: 36,
    minHeight: 48,
  },
  inboxSearchIcon: {
    position: 'absolute',
    left: DS.space.base,
  },
  inboxSearchInput: {
    flex: 1,
    fontFamily: DS.font.body,
    fontSize: 14,
    color: c.text,
    paddingVertical: DS.space.md,
    paddingRight: DS.space.base,
  },
  inboxRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: DS.space.md,
    padding: DS.space.base,
    borderLeftWidth: 2,
  },
  inboxRowSelected: {
    backgroundColor: 'rgba(28, 28, 28, 0.2)',
    borderLeftColor: c.gold,
  },
  inboxRowIdle: {
    borderLeftColor: 'transparent',
  },
  inboxAvatarWrap: {
    position: 'relative',
  },
  inboxAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
  },
  inboxAvatarGoldRing: {
    borderWidth: 2,
    borderColor: c.gold,
  },
  inboxOnlineDot: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: c.onlineGreen,
    borderWidth: 2,
    borderColor: c.background,
  },
  inboxMid: {
    flex: 1,
    minWidth: 0,
  },
  inboxNameRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  inboxName: {
    fontFamily: DS.font.bodyMedium,
    fontSize: 14,
    color: c.text,
    flex: 1,
    marginRight: DS.space.sm,
  },
  inboxTime: {
    fontSize: 12,
    color: c.textMuted,
  },
  inboxEmpty: {
    fontFamily: DS.font.body,
    fontSize: 14,
    color: c.textMuted,
    textAlign: 'center',
    marginTop: DS.space.xl,
    paddingHorizontal: DS.space.xl,
    lineHeight: 20,
  },
  inboxPreview: {
    fontFamily: DS.font.body,
    fontSize: 14,
    color: c.text,
  },
  inboxPreviewMuted: {
    fontFamily: DS.font.body,
    fontSize: 14,
    color: c.textMuted,
  },
  inboxUnreadBadge: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: c.gold,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 2,
  },
  inboxUnreadBadgeTxt: {
    fontSize: 11,
    fontFamily: DS.font.bodyBold,
    color: c.background,
  },
  threadHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: DS.space.base,
    paddingBottom: DS.space.md,
    gap: DS.space.sm,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: c.borderWhite5,
  },
  threadHeaderAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
  },
  threadHeaderAvatarGoldRing: {
    borderWidth: 2,
    borderColor: c.gold,
  },
  threadHeaderMenuBtn: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
    backgroundColor: c.goldTint10,
    borderWidth: 1,
    borderColor: c.goldTint30,
  },
  threadSearchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: DS.space.sm,
    paddingHorizontal: DS.space.base,
    paddingVertical: DS.space.sm,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: c.borderWhite5,
  },
  threadSearchInput: {
    flex: 1,
    fontFamily: DS.font.body,
    fontSize: 15,
    color: c.text,
    paddingVertical: DS.space.sm,
  },
  bubbleMedia: {
    width: 220,
    height: 160,
    borderRadius: DS.radius.lg,
    marginBottom: DS.space.xs,
  },
  threadHeaderMid: {
    flex: 1,
    minWidth: 0,
    marginRight: DS.space.xs,
  },
  threadHeaderName: {
    fontFamily: DS.font.heading,
    fontSize: 22,
    color: c.text,
    letterSpacing: 1,
  },
  threadHeaderStatus: {
    fontFamily: DS.font.body,
    fontSize: 12,
    color: c.onlineGreen,
  },
  threadHeaderActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
    flexShrink: 0,
  },
  threadHeaderIcon: {
    padding: DS.space.sm,
  },
  threadDayPillWrap: {
    alignItems: 'center',
    marginBottom: DS.space.md,
  },
  threadEmpty: {
    fontFamily: DS.font.body,
    fontSize: 14,
    color: c.textMuted,
    textAlign: 'center',
    marginVertical: DS.space.lg,
    paddingHorizontal: DS.space.lg,
  },
  threadDayPill: {
    fontFamily: DS.font.body,
    fontSize: 12,
    color: c.textMuted,
    backgroundColor: c.surface,
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: DS.radius.pill,
    overflow: 'hidden',
  },
  threadMsgThem: {
    alignSelf: 'flex-start',
    maxWidth: 280,
    marginBottom: DS.space.md,
  },
  threadMsgMe: {
    alignSelf: 'flex-end',
    maxWidth: 280,
    marginBottom: DS.space.md,
  },
  bubbleMetaThem: {
    fontFamily: DS.font.body,
    fontSize: 12,
    color: c.textMuted,
    marginLeft: DS.space.sm,
    marginTop: 4,
  },
  bubbleMetaMeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    alignSelf: 'flex-end',
    marginTop: 4,
  },
  bubbleMetaMe: {
    fontFamily: DS.font.body,
    fontSize: 12,
    color: c.textMuted,
  },
  composeBar: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    paddingHorizontal: DS.space.base,
    paddingTop: DS.space.md,
    gap: DS.space.md,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: c.borderWhite5,
    backgroundColor: c.background,
  },
  composePlus: {
    padding: DS.space.sm,
    marginBottom: 4,
  },
  composeInputRounded: {
    flex: 1,
    backgroundColor: c.surface,
    borderRadius: DS.radius.xl,
    borderWidth: 1,
    borderColor: c.border,
    paddingHorizontal: DS.space.base,
    paddingVertical: DS.space.md,
    fontFamily: DS.font.body,
    fontSize: 14,
    color: c.text,
    maxHeight: 120,
  },
  sendBtnRound: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: c.gold,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 2,
  },
  brandTopNav: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: DS.space.base,
    paddingBottom: DS.space.md,
    backgroundColor: c.surfaceFloating92,
    borderBottomWidth: 1,
    borderBottomColor: c.surface,
  },
  brandNavBtn: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
  },
  brandNavTitle: {
    ...tabRootTitleText,
    flex: 1,
    textAlign: 'center',
  },
  brandScroll: {
    paddingHorizontal: DS.space.base,
  },
  brandHero: {
    alignItems: 'center',
    paddingTop: DS.space.lg,
    paddingBottom: DS.space.xl,
  },
  brandLogoCard: {
    width: '100%',
    backgroundColor: c.surface,
    borderRadius: 10,
    padding: DS.space.xl,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: DS.space.lg,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: c.borderWhite5,
  },
  brandHeroTitle: {
    fontFamily: DS.font.heading,
    fontSize: 36,
    color: c.text,
    letterSpacing: 2,
    marginBottom: DS.space.sm,
  },
  brandActiveRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: DS.space.sm,
  },
  brandActiveDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: c.onlineGreen,
  },
  brandActiveLabel: {
    fontFamily: DS.font.bodyMedium,
    fontSize: 12,
    color: c.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 2,
  },
  brandQuoteSection: {
    flexDirection: 'row',
    gap: DS.space.base,
    paddingVertical: DS.space.lg,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: c.surface,
  },
  brandQuoteKicker: {
    fontFamily: DS.font.bodyMedium,
    fontSize: 11,
    color: c.gold,
    letterSpacing: 1.5,
    textTransform: 'uppercase',
    marginBottom: DS.space.sm,
  },
  brandQuoteBody: {
    fontFamily: DS.font.body,
    fontSize: 14,
    fontStyle: 'italic',
    fontWeight: '300',
    color: c.textMuted,
    lineHeight: 22,
  },
  brandPromoBlock: {
    paddingVertical: DS.space.xl,
    alignItems: 'center',
  },
  brandPromoHeadingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: DS.space.base,
  },
  brandPromoHeading: {
    fontFamily: DS.font.bodyMedium,
    fontSize: 12,
    color: c.gold,
    letterSpacing: 2,
    textTransform: 'uppercase',
  },
  brandCodeRow: {
    width: '100%',
    maxWidth: 280,
    marginTop: DS.space.sm,
  },
  brandCodeBox: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: c.gold,
    borderRadius: DS.radius.md,
    backgroundColor: 'rgba(10, 10, 10, 0.8)',
    padding: DS.space.base,
  },
  brandCodeText: {
    flex: 1,
    fontFamily: DS.font.bodyBold,
    fontSize: 16,
    color: c.gold,
    letterSpacing: 4,
    textAlign: 'center',
  },
  brandCopyBtn: {
    width: 32,
    height: 32,
    borderRadius: DS.radius.sm,
    backgroundColor: c.goldTint10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  brandCodeHint: {
    fontFamily: DS.font.body,
    fontSize: 11,
    color: c.textMuted,
    textAlign: 'center',
    marginTop: DS.space.md,
    paddingHorizontal: DS.space.lg,
  },
  brandAbout: {
    paddingVertical: DS.space.lg,
  },
  brandAboutTitle: {
    fontFamily: DS.font.heading,
    fontSize: 20,
    color: c.text,
    textTransform: 'uppercase',
    letterSpacing: 1.5,
    marginBottom: DS.space.sm,
  },
  brandAboutBody: {
    fontFamily: DS.font.body,
    fontSize: 16,
    color: c.text,
    lineHeight: 26,
    marginBottom: DS.space.md,
  },
  brandTagRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: DS.space.sm,
  },
  brandTag: {
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: DS.radius.pill,
    backgroundColor: c.surface,
  },
  brandTagText: {
    fontFamily: DS.font.body,
    fontSize: 11,
    color: c.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 2,
  },
  brandFeaturedVideo: {
    marginVertical: DS.space.lg,
    borderRadius: 10,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: c.surface,
    position: 'relative',
  },
  brandVideoImg: {
    width: '100%',
    aspectRatio: 16 / 9,
    opacity: 0.6,
  },
  brandVideoScrim: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.4)',
  },
  brandPlayCircle: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    marginLeft: -28,
    marginTop: -28,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: 'rgba(10,10,10,0.8)',
    borderWidth: 1,
    borderColor: c.goldTint30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  brandDurationBadge: {
    position: 'absolute',
    bottom: 12,
    left: 12,
    backgroundColor: 'rgba(10,10,10,0.8)',
    paddingHorizontal: DS.space.sm,
    paddingVertical: 4,
    borderRadius: DS.radius.sm,
  },
  brandDurationText: {
    fontFamily: DS.font.bodyBold,
    fontSize: 10,
    color: c.text,
  },
  brandProductsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    marginBottom: DS.space.md,
  },
  brandProductsTitle: {
    fontFamily: DS.font.bodyMedium,
    fontSize: 14,
    color: c.text,
    textTransform: 'uppercase',
    letterSpacing: 2,
  },
  brandViewAll: {
    fontFamily: DS.font.bodyMedium,
    fontSize: 11,
    color: c.gold,
    textTransform: 'uppercase',
    letterSpacing: 2,
  },
  brandProductsScroll: {
    gap: DS.space.base,
    paddingBottom: DS.space.lg,
  },
  brandProductCard: {
    width: 140,
  },
  brandProductThumb: {
    aspectRatio: 1,
    backgroundColor: c.surface,
    borderRadius: DS.radius.lg,
    marginBottom: DS.space.sm,
    padding: DS.space.base,
    borderWidth: 1,
    borderColor: c.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  brandProductImg: {
    width: '100%',
    height: '100%',
  },
  brandProductTitle: {
    fontFamily: DS.font.bodyMedium,
    fontSize: 13,
    color: c.text,
  },
  brandProductPrice: {
    fontFamily: DS.font.body,
    fontSize: 12,
    color: c.textMuted,
    marginTop: 4,
  },
  brandFooter: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: DS.space.base,
    paddingTop: DS.space.md,
    backgroundColor: c.surfaceFloating92,
    borderTopWidth: 1,
    borderTopColor: c.surface,
  },
  brandVisitCta: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: DS.space.md,
    paddingVertical: DS.space.base,
    borderWidth: 1,
    borderColor: c.gold,
    backgroundColor: 'rgba(10,10,10,0.5)',
    borderRadius: 2,
  },
  brandVisitText: {
    fontFamily: DS.font.heading,
    fontSize: 14,
    color: c.gold,
    letterSpacing: 2,
    marginTop: 2,
  },
  simpleHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: DS.space.lg,
    paddingVertical: DS.space.lg,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: c.borderHairline,
  },
  simpleTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: c.text,
    flex: 1,
    textAlign: 'center',
  },
  padded: {
    padding: DS.space.lg,
  },
  muted: {
    color: c.textMuted,
    fontSize: 14,
    lineHeight: 20,
  },
  gold: {
    color: c.gold,
    fontWeight: '600',
  },
  resultRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: DS.space.md,
    paddingVertical: DS.space.md,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: c.borderHairline,
  },
  resultAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
  },
  notifRow: {
    flexDirection: 'row',
    gap: DS.space.md,
    paddingVertical: DS.space.md,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: c.borderHairline,
  },
  notifDotLg: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: c.gold,
    marginTop: 6,
  },
  threadRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: DS.space.md,
    paddingVertical: DS.space.md,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: c.borderHairline,
  },
  threadAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: c.input,
  },
  threadTime: {
    fontSize: 12,
    color: c.textMuted,
  },
  threadBody: {
    padding: DS.space.lg,
    gap: DS.space.sm,
  },
  bubbleThem: {
    backgroundColor: c.surface,
    paddingHorizontal: DS.space.base,
    paddingVertical: DS.space.md,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    borderBottomRightRadius: 16,
    borderBottomLeftRadius: 6,
  },
  bubbleMe: {
    backgroundColor: c.gold,
    paddingHorizontal: DS.space.base,
    paddingVertical: DS.space.md,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 6,
  },
  bubbleText: {
    color: c.text,
    fontSize: 14,
    lineHeight: 20,
    fontFamily: DS.font.body,
  },
  bubbleTextDark: {
    color: c.background,
    fontSize: 14,
    lineHeight: 20,
    fontFamily: DS.font.body,
  },
  composeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: DS.space.md,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: c.borderHairline,
    gap: DS.space.sm,
  },
  composeInput: {
    flex: 1,
    backgroundColor: c.input,
    borderRadius: DS.radius.pill,
    paddingHorizontal: DS.space.base,
    paddingVertical: DS.space.sm,
    color: c.text,
  },
  sendBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: c.gold,
    alignItems: 'center',
    justifyContent: 'center',
  },
  backLink: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: DS.space.lg,
  },
  heroBrand: {
    fontSize: 32,
    fontWeight: '700',
    color: c.gold,
    letterSpacing: 1,
    textTransform: 'uppercase',
    marginBottom: DS.space.sm,
  },
  card: {
    marginTop: DS.space.xl,
    padding: DS.space.lg,
    backgroundColor: c.surface,
    borderRadius: DS.radius.xl,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: c.cardBorder,
  },
  primaryMini: {
    marginTop: DS.space.lg,
    backgroundColor: c.gold,
    paddingVertical: DS.space.md,
    borderRadius: DS.radius.lg,
    alignItems: 'center',
  },
  primaryMiniText: {
    color: c.background,
    fontWeight: '700',
  },
  hubPad: {
    padding: DS.space.lg,
    paddingBottom: 48,
  },
  hubKicker: {
    fontSize: 12,
    letterSpacing: 3,
    color: c.gold,
    marginBottom: DS.space.sm,
  },
  hubTitle: {
    ...tabRootTitleText,
    marginBottom: DS.space.md,
  },
  hubBody: {
    color: c.textMuted,
    marginBottom: DS.space.xl,
    lineHeight: 22,
  },
  hubBtn: {
    backgroundColor: c.gold,
    paddingVertical: DS.space.md,
    borderRadius: DS.radius.xl,
    alignItems: 'center',
    marginBottom: DS.space.md,
  },
  hubBtnText: {
    color: c.background,
    fontWeight: '700',
    fontSize: 14,
  },
  hubClose: {
    alignItems: 'center',
    marginTop: DS.space.lg,
  },
  });
}
