/**
 * DaltonProject demo — canonical relative paths (spaces preserved for static servers).
 * Use from static HTML via shared/demo-shell.js or inline hrefs.
 */
window.DEMO_ROUTES = {
  index: 'demo.html',
  login: '1-Onboarding Flow - Log In.html',
  verifyReset: '2-Onboarding Flow - Verify Reset.html',
  forgotPassword: '3-Onboarding Flow - Forgot Passw.html',
  welcome: '4-Onboarding Flow - Welcome & Ac.html',
  createPassword: '5-Onboarding Flow - Create New P.html',
  brandPartner: '6-Brand Partner Detail.html',
  communityFeed: '7-Community Feed.html',
  eventDetails: '8-Event Booking - Event Details.html',
  confirmAttend: '9-Event Booking - Confirm Attend.html',
  bookingConfirm: '10-Event Booking - Booking Confir.html',
  savedEvents: '11-Event Booking - Saved Events.html',
  myBookings: '12-Event Booking - My Bookings.html',
  upcomingEvents: '13-Upcoming Events.html',
  settings: '14-Profile Settings - Settings.html',
  editBasic: '15-Profile Settings - Edit Basic.html',
  editPhoto: '16-Profile Settings - Edit Profil.html',
  editAthlete: '17-Profile Settings - Edit Athlet.html',
  mediaLibrary: '18-Media Library.html',
  mediaSearchResults: '19-Media Player - Media Search Re.html',
  mediaPlayer: '20-Media Player - Media Player.html',
  savedMedia: '21-Media Player - Saved Media.html',
  athleteProfile: '22-Athlete Profile.html',
  mediaSearch: '23-Media Player - Media Search.html',
  communityFeedMedia: '24-Media Player - Community Feed.html',
  communitySearchResults: '25-Community Flow - Community Sea.html',
  notifications: '26-Community Flow - Notifications.html',
  messagesInbox: '27-Community Flow - Messages Inbo.html',
  messageThread: '28-Community Flow - Message Threa.html',
  communitySearch: '29-Community Flow - Community Sea.html',
  editProfileSections: '30-Profile Settings - Edit Profil.html',
  sponsorListings: '31-Sponsor Listings.html',
  grantAccess: '32-The Dalton Grant Academy.html',
};
